apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: animated-sustain-hpa
  namespace: animated-sustain-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: animated-sustain
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80